<?php

return [
    'years_in_school' => [
        'Year 7',
        'Year 8',
        'Year 9',
        'Year 10',
        'Year 11',
    ],
    'subjects' => [
        'Maths',
        'Science',
        'English',
        'History',
        'Geography',
        'Spanish',
        'French',
        'German',
        'Italian',
        'Physics',
        'Chemistry',
        'Biology',
        'Art',
        'Design Technology',
        'Physical Education',
        'Religious Studies',
        'Music',
        'Drama',
        'Computer Science',
        'Business Studies',
        'Citizenship',
        'Psychology',
        'Sociology',
        'Philosophy',
        'Law',
        'Economics',
        'Health & Social Care',
        'ICT',
        'Media Studies',
        'Food Technology',
        'Engineering',
    ],
    'exam_boards' => [
        'AQA',
        'Edexcel',
        'OCR',
        'CIE',
        'WJEC',
        'Pearson',
    ],
    'topics' => [
        // Maths Topics
        'Algebra',
        'Geometry',
        'Trigonometry',
        'Statistics',
        'Probability',
        'Linear Equations',
        'Quadratic Equations',
        'Polynomials',
        'Simultaneous Equations',
        'Inequalities',
        'Pythagoras\' Theorem',
        'Circle Theorems',
        'Coordinate Geometry',
        'Vectors',
        'Functions and Graphs',
        'Surds',
        'Logarithms',
        'Sequences and Series',

        // Science Topics
        'Atoms and Elements',
        'Chemical Reactions',
        'Acids and Bases',
        'Periodic Table',
        'Cells and Microorganisms',
        'Energy Transfer',
        'Forces and Motion',
        'Electricity',
        'Magnetism',
        'Photosynthesis',
        'Genetics and Evolution',
        'Chemical Bonding',
        'Atoms and Molecules',
        'Work and Energy',
        'Heat and Temperature',
        'Waves and Sound',
        'Light and Optics',

        // History Topics
        'Medieval Britain',
        'The Tudors',
        'The Industrial Revolution',
        'World War I',
        'World War II',
        'The Cold War',
        'The Norman Conquest',
        'The British Empire',
        'Victorian Britain',
        'The Civil Rights Movement',
        'The Russian Revolution',
        'The Rise of Nazi Germany',
        'Ancient Greece',
        'Ancient Rome',
        'The Middle Ages',
        'The Renaissance',

        // Geography Topics
        'Physical Geography',
        'Human Geography',
        'Climate Change',
        'Urbanization',
        'Coastal Erosion',
        'River Processes',
        'Population Growth',
        'Geographical Information Systems (GIS)',
        'Sustainable Development',
        'Environmental Issues',
        'Hazardous Earth',
        'Weathering and Erosion',
        'Plate Tectonics',
        'Natural Disasters',
        'World Resources',

        // Languages Topics (Spanish, French, German, etc.)
        'Vocabulary Building',
        'Grammar and Syntax',
        'Tenses (Present, Past, Future)',
        'Conjugation of Verbs',
        'Idiomatic Expressions',
        'Cultural Context',
        'Translation Skills',
        'Listening Comprehension',
        'Reading Comprehension',
        'Oral Production',
        'Writing Skills',
        'Formal vs Informal Language',

        // Computing & ICT Topics
        'Programming',
        'Algorithms',
        'Data Structures',
        'Database Management',
        'Networks',
        'Cybersecurity',
        'Web Development',
        'Artificial Intelligence',
        'Robotics',
        'Digital Literacy',
        'Computer Hardware',
        'Software Development',
        'Operating Systems',
        'Data Privacy',
        'Cloud Computing',
        'E-commerce',
        'Social Media Management',

        // Other Topics
        'Art Techniques',
        'Drama Performance',
        'Musical Composition',
        'Sociology of Education',
        'Psychological Theories',
        'Human Rights',
        'Social Justice',
        'Business Strategies',
        'Public Relations',
        'Advertising',
        'Law and Order',
        'International Relations',
        'Globalization',
        'Philosophical Ethics',
        'Nutrition and Health',
    ]
];
