<?php

return [

    'quantity' => [
        '5',
        '10',
        '20',
    ],
    'years_in_school' => [
        'Year 7',
        'Year 8',
        'Year 9',
        'Year 10',
        'Year 11',
    ],
    'subjects' => [
        'English Literature',
        'English Language',
        'Maths',
        'Physics',
        'Chemistry',
        'Biology',
        'History',
        'Geography',
        'Spanish',
        'French',
        'German',
        'Italian',
        'Art',
        'Design Technology',
        'Physical Education',
        'Religious Studies',
        'Music',
        'Drama',
        'Computer Science',
        'Business Studies',
        'Psychology',
        'Sociology',
        'Philosophy',
        'Economics',
        'Health & Social Care',
        'ICT',
        'Media Studies',
        'Food Technology',
    ],
    'exam_boards' => [
        'AQA',
        'Edexcel',
        'OCR',
        'CIE',
        'WJEC',
        'Pearson',
    ],
    'exam_boards_by_subject' => [
        'Maths' => ['AQA', 'Edexcel', 'OCR', 'WJEC'],
        'Biology' => ['AQA', 'Edexcel', 'OCR', 'CIE', 'WJEC'],
        'Chemistry' => ['AQA', 'Edexcel', 'OCR', 'CIE', 'WJEC'],
        'Physics' => ['AQA', 'Edexcel', 'OCR', 'CIE', 'WJEC'],
        'History' => ['AQA', 'OCR', 'Edexcel'],
        'Geography' => ['AQA', 'Edexcel', 'OCR', 'WJEC'],
        'Computer Science' => ['AQA', 'OCR', 'Edexcel'],
        'Art' => ['AQA', 'Edexcel', 'WJEC'],
        'Drama' => ['AQA', 'OCR', 'Edexcel'],
        'Music' => ['AQA', 'Edexcel', 'WJEC'],
        'Spanish' => ['AQA', 'Edexcel', 'CIE'],
        'French' => ['AQA', 'Edexcel', 'CIE'],
        'German' => ['AQA', 'Edexcel', 'CIE'],
        'Italian' => ['AQA', 'Edexcel', 'CIE'],
        'Psychology' => ['AQA', 'OCR'],
        'Sociology' => ['AQA', 'OCR'],
        'Philosophy' => ['AQA'],
        'Business Studies' => ['AQA', 'Edexcel', 'OCR'],
        'Economics' => ['AQA', 'Edexcel', 'OCR'],
        'ICT' => ['Edexcel', 'OCR', 'WJEC'],
        'Media Studies' => ['AQA', 'Edexcel', 'OCR'],
        'Food Technology' => ['AQA', 'Edexcel', 'WJEC'],
        'Design Technology' => ['AQA', 'Edexcel', 'OCR'],
        'Physical Education' => ['AQA', 'Edexcel', 'OCR'],
        'Religious Studies' => ['AQA', 'Edexcel', 'OCR'],
        'Health & Social Care' => ['AQA', 'Edexcel', 'OCR'],
        'English Language' => ['AQA', 'Edexcel', 'OCR', 'WJEC'],
        'English Literature' => ['AQA', 'Edexcel', 'OCR', 'WJEC'],
    ],

    'topics' => [
        'maths' =>[
            'Algebra',
            'Geometry',
            'Trigonometry',
            'Statistics',
            'Probability',
            'Linear Equations',
            'Quadratic Equations',
            'Polynomials',
            'Simultaneous Equations',
            'Inequalities',
            'Pythagoras\' Theorem',
            'Circle Theorems',
            'Coordinate Geometry',
            'Vectors',
            'Functions and Graphs',
            'Surds',
            'Logarithms',
            'Sequences and Series'
        ],

       'biology' => [
            'Cells and Microorganisms',
            'Genetics and Evolution',
            'Photosynthesis',
            'Health and Disease',
            'Biodiversity and Conservation',
            'Human Anatomy and Physiology',
            'Respiration',
            'The Nervous System',
            'Reproduction and Inheritance',
            'Enzymes and Digestion',
            'Ecology and Ecosystems',
            'Microorganisms and Disease',
            'Genetic Engineering',
            'Cell Division',
            'Human Impact on the Environment',
        ],

        'physics' => [
            'Forces and Motion',
            'Energy Transfer',
            'Electricity',
            'Magnetism',
            'Waves and Sound',
            'Light and Optics',
            'Atomic Structure',
            'Radioactivity',
            'Forces in Fluids',
            'Space Physics',
            'Momentum and Impulse',
            'Work and Energy',
            'Gravitational Fields',
            'Mechanical Waves',
            'Thermodynamics',
            'Nuclear Energy',
        ],

        'chemistry' => [
            'Atoms and Elements',
            'Chemical Reactions',
            'Acids and Bases',
            'Periodic Table',
            'Chemical Bonding',
            'Atoms and Molecules',
            'Moles and Stoichiometry',
            'States of Matter',
            'Electrolysis',
            'Organic Chemistry',
            'Redox Reactions',
            'Thermodynamics in Chemistry',
            'Rates of Reaction',
            'Equilibrium and Le Chatelier\'s Principle',
            'Acid-Base Equilibria',
            'Industrial Chemistry',
        ],
        'english_language' => [
            'Reading Comprehension',
            'Understanding Texts',
            'Identifying Key Themes',
            'Inference and Interpretation',
            'Language Analysis',
            'Descriptive Writing',
            'Narrative Writing',
            'Persuasive Writing',
            'Creative Writing',
            'Writing for Different Audiences and Purposes',
            'Sentence Structure',
            'Tenses',
            'Clauses and Phrases',
            'Punctuation Rules (commas, apostrophes, etc.)',
            'Spelling Rules',
            'Expanding Vocabulary',
            'Synonyms and Antonyms',
            'Group Discussions',
            'Formal Presentations',
            'Debating',
            'Listening Comprehension',
        ],

        'english_literature' => [
            'Romeo and Juliet by William Shakespeare',
            'Macbeth by William Shakespeare',
            'A Midsummer Night\'s Dream by William Shakespeare',
            'Julius Caesar by William Shakespeare',
            'The Tempest by William Shakespeare',
            'Frankenstein by Mary Shelley',
            'Dracula by Bram Stoker',
            'Great Expectations by Charles Dickens',
            'Jane Eyre by Charlotte Brontë',
            'Of Mice and Men by John Steinbeck',
            'To Kill a Mockingbird by Harper Lee',
            'An Inspector Calls by J.B. Priestley',
            'Lord of the Flies by William Golding',
            'Poetry Analysis',
            'Exploring Different Poetry Forms (sonnets, free verse, etc.)',
            'William Blake (Poet)',
            'Robert Frost (Poet)',
            'John Keats (Poet)',
            'Character Analysis in Drama',
            'Themes in Plays',
            'Dramatic Devices (soliloquies, irony, etc.)',
            'Personal Conflict and Identity in Literature',
            'Social Conflict and Identity in Literature',
        ],


        'history' => [
            'Medieval Britain',
            'The Tudors',
            'The Industrial Revolution',
            'World War I',
            'World War II',
            'The Cold War',
            'The Norman Conquest',
            'The British Empire',
            'Victorian Britain',
            'The Civil Rights Movement',
            'The Russian Revolution',
            'The Rise of Nazi Germany',
            'Ancient Greece',
            'Ancient Rome',
            'The Middle Ages',
            'The Renaissance',
        ],

        'geography' => [
            'Physical Geography',
            'Human Geography',
            'Climate Change',
            'Urbanization',
            'Coastal Erosion',
            'River Processes',
            'Population Growth',
            'Geographical Information Systems GIS',
            'Sustainable Development',
            'Environmental Issues',
            'Hazardous Earth',
            'Weathering and Erosion',
            'Plate Tectonics',
            'Natural Disasters',
            'World Resources',
        ],

        'computing_ict' => [
            'Programming',
            'Algorithms',
            'Data Structures',
            'Database Management',
            'Networks',
            'Cybersecurity',
            'Web Development',
            'Artificial Intelligence',
            'Robotics',
            'Digital Literacy',
            'Computer Hardware',
            'Software Development',
            'Operating Systems',
            'Data Privacy',
            'Cloud Computing',
            'E-commerce',
            'Social Media Management',
        ],
        
        'spanish' => [
            'Grammar and Syntax',
            'Vocabulary',
            'Cultural Topics',
            'Communication Skills',
            'Translation Skills',
            'Tenses and Modality',
            'Pronunciation',
            'Family and Relationships',
            'Daily Routine and Time',
            'School and Education',
            'Hobbies and Free Time',
            'Travel and Transport',
            'Holidays and Festivals',
            'Food and Drink',
            'Weather and Climate',
            'Work and Careers',
            'Home and Environment',
            'Health and Well-being',
            'Shopping and Money',
            'Technology and Social Media',
            'Sports and Leisure',
            'Environment and Sustainability',
            'Traditions and Celebrations',
            'Geography and Landmarks',
            'History and Politics',
            'Literature',
            'Music, Film, and Arts',
            'Customs and Social Norms',
            'Festivals and National Holidays',
            'Food and Regional Cuisine',
        ],

        'french' => [
            'Grammar and Syntax',
            'Vocabulary',
            'Cultural Topics',
            'Communication Skills',
            'Translation Skills',
            'Tenses and Modality',
            'Pronunciation',
            'Family and Relationships',
            'Daily Routine and Time',
            'School and Education',
            'Hobbies and Free Time',
            'Travel and Transport',
            'Holidays and Festivals',
            'Food and Drink',
            'Weather and Climate',
            'Work and Careers',
            'Home and Environment',
            'Health and Well-being',
            'Shopping and Money',
            'Technology and Social Media',
            'Sports and Leisure',
            'Environment and Sustainability',
            'Traditions and Celebrations',
            'Geography and Landmarks',
            'History and Politics',
            'Literature',
            'Music, Film, and Arts',
            'Customs and Social Norms',
            'Festivals and National Holidays',
            'Food and Regional Cuisine',
        ],

        'german' => [
            'Grammar and Syntax',
            'Vocabulary',
            'Cultural Topics',
            'Communication Skills',
            'Translation Skills',
            'Tenses and Modality',
            'Pronunciation',
            'Family and Relationships',
            'Daily Routine and Time',
            'School and Education',
            'Hobbies and Free Time',
            'Travel and Transport',
            'Holidays and Festivals',
            'Food and Drink',
            'Weather and Climate',
            'Work and Careers',
            'Home and Environment',
            'Health and Well-being',
            'Shopping and Money',
            'Technology and Social Media',
            'Sports and Leisure',
            'Environment and Sustainability',
            'Traditions and Celebrations',
            'Geography and Landmarks',
            'History and Politics',
            'Literature',
            'Music, Film, and Arts',
            'Customs and Social Norms',
            'Festivals and National Holidays',
            'Food and Regional Cuisine',
        ],

        'italian' => [
            'Grammar and Syntax',
            'Vocabulary',
            'Cultural Topics',
            'Communication Skills',
            'Translation Skills',
            'Tenses and Modality',
            'Pronunciation',
            'Family and Relationships',
            'Daily Routine and Time',
            'School and Education',
            'Hobbies and Free Time',
            'Travel and Transport',
            'Holidays and Festivals',
            'Food and Drink',
            'Weather and Climate',
            'Work and Careers',
            'Home and Environment',
            'Health and Well-being',
            'Shopping and Money',
            'Technology and Social Media',
            'Sports and Leisure',
            'Environment and Sustainability',
            'Traditions and Celebrations',
            'Geography and Landmarks',
            'History and Politics',
            'Literature',
            'Music, Film, and Arts',
            'Customs and Social Norms',
            'Festivals and National Holidays',
            'Food and Regional Cuisine',
        ],
        'art' => [
            'Drawing and Sketching Techniques',
            'Colour Theory',
            'Painting Techniques',
            'Sculpture and 3D Art',
            'Printmaking',
            'Art History',
            'Contemporary Art',
            'Surrealism',
            'Abstract Art',
            'Portraiture',
            'Landscape Painting',
            'Still Life',
            'Photography',
            'Digital Art',
            'Textile Arts',
            'Ceramics',
            'Composition and Design',
            'Visual Communication',
        ],

        'design_technology' => [
            'Design Process',
            'Materials and Components',
            'Product Design',
            'Sustainable Design',
            '3D Modelling and CAD',
            'Mechanical Systems',
            'Electronic Systems',
            'Control Systems',
            'Timber and Woodworking',
            'Metalworking',
            'Textiles and Fashion Design',
            'Food Technology',
            'Construction Materials',
            'Engineering Design',
            'Rapid Prototyping',
            'Technical Drawing',
            'Product Testing and Evaluation',
        ],

        'physical_education' => [
            'Fitness and Health',
            'Exercise Physiology',
            'Sports Science',
            'Anatomy and Physiology',
            'Team Sports',
            'Individual Sports',
            'Sports Coaching',
            'Movement and Coordination',
            'Sports Psychology',
            'Nutrition and Performance',
            'Injury Prevention and Rehabilitation',
            'Sports Leadership',
            'Physical Training Programs',
            'Biomechanics',
            'Health Education',
            'Outdoor Education',
            'Physical Activity and Well-being',
        ],

        'religious_studies' => [
            'Beliefs and Practices',
            'The Life and Teachings of Jesus',
            'The Five Pillars of Islam',
            'Hinduism and the Bhagavad Gita',
            'Buddhism and Meditation',
            'Religious Ethics and Morality',
            'Religious Rituals and Symbols',
            'The Role of Religion in Society',
            'Religious and Secular Worldviews',
            'Sacred Texts (Bible, Qur\'an, Vedas)',
            'Life After Death and the Afterlife',
            'Religious Diversity and Interfaith Dialogue',
            'Religion and Politics',
            'Religion and Science',
            'Social Justice and Human Rights',
            'Religion and Conflict',
            'Global Religion and Secularism',
        ],

        'music' => [
            'Musical Theory',
            'Harmony and Chords',
            'Rhythm and Time Signatures',
            'Music History (Classical, Baroque, etc.)',
            'Instrumentation and Orchestration',
            'Voice and Choir',
            'Music Technology and Production',
            'Genres of Music (Rock, Jazz, Classical)',
            'Composition and Songwriting',
            'Musical Analysis',
            'Performance Techniques',
            'Sight Reading and Ear Training',
            'Music and Emotion',
            'World Music and Folk Traditions',
            'Music and Society',
            'Music in Film and Media',
            'Music Business and Marketing',
        ],

        'drama' => [
            'Acting Techniques',
            'Stagecraft and Production',
            'Theatrical History (Shakespeare, Modern Drama)',
            'Directing and Performance Styles',
            'Scriptwriting and Playwriting',
            'Improvisation',
            'Voice and Speech Training',
            'Character Development',
            'Movement and Physical Theatre',
            'Lighting and Sound Design',
            'Costume and Set Design',
            'Theatrical Genres (Tragedy, Comedy, etc.)',
            'Drama and Social Issues',
            'Theatre Criticism and Review',
            'Pantomime and Mime',
            'Devising and Collaborative Theatre',
            'Live Theatre vs. Screen Acting',
            'Theatre in Education',
        ],
        'business_studies' => [
            'Business Structures and Ownership',
            'Marketing and Advertising',
            'Human Resources Management',
            'Financial Management and Accounting',
            'Entrepreneurship',
            'Operations Management',
            'Business Ethics and Corporate Social Responsibility (CSR)',
            'International Trade and Globalization',
            'Business Law',
            'Market Research and Consumer Behavior',
            'Leadership and Management Styles',
            'Organizational Culture',
            'Business Planning and Strategy',
            'Business Growth and Expansion',
            'Digital Marketing and E-commerce',
            'Financial Planning and Budgeting',
            'Business Startups and Small Businesses',
        ],

        'psychology' => [
            'Cognitive Psychology',
            'Social Psychology',
            'Developmental Psychology',
            'Biopsychology and Neuroscience',
            'Learning Theories',
            'Mental Health and Disorders',
            'Research Methods in Psychology',
            'Personality Psychology',
            'Psychological Theories (Freud, Jung, etc.)',
            'Motivation and Emotion',
            'Abnormal Psychology',
            'Psychological Testing and Assessment',
            'Perception and Sensation',
            'Psychological Disorders Treatment',
            'Psychology of Groups and Leadership',
            'Health Psychology',
            'Psychology and Education',
        ],

        'sociology' => [
            'Sociological Theories (Marxism, Functionalism, etc.)',
            'Socialization and Identity',
            'Class, Gender, and Ethnicity',
            'Family and Relationships',
            'Crime and Deviance',
            'Education and Social Mobility',
            'Media and Society',
            'Globalization and Social Change',
            'Social Inequality',
            'Social Research Methods',
            'Work and Employment',
            'Health and Medicine in Society',
            'Social Problems and Social Policy',
            'Religion and Society',
            'Poverty and Social Exclusion',
            'Youth Culture and Subcultures',
            'Social Movements and Collective Behavior',
        ],

        'philosophy' => [
            'Epistemology (Theory of Knowledge)',
            'Ethics and Moral Philosophy',
            'Political Philosophy',
            'Metaphysics',
            'Philosophy of Mind and Consciousness',
            'Philosophy of Language',
            'Philosophical Logic',
            'Existentialism',
            'Philosophy of Religion',
            'Aesthetics and the Philosophy of Art',
            'Philosophical Theories of Free Will',
            'Rationalism vs. Empiricism',
            'The Philosophy of Science',
            'Philosophy of History',
            'Philosophy of Law',
            'Feminist Philosophy',
            'Eastern Philosophy (Buddhism, Taoism, etc.)',
        ],

        'economics' => [
            'Microeconomics',
            'Macroeconomics',
            'Supply and Demand',
            'Market Structures (Perfect Competition, Monopoly, etc.)',
            'Government Intervention and Regulation',
            'Economic Systems (Capitalism, Socialism, etc.)',
            'International Trade and Global Economics',
            'Fiscal and Monetary Policy',
            'Inflation, Unemployment, and Economic Growth',
            'Labour Markets and Employment',
            'Market Failures and Externalities',
            'Development Economics',
            'Environmental Economics',
            'Public Finance and Taxation',
            'Economic Inequality and Poverty',
            'Globalization and Trade Policies',
            'The Role of Central Banks and Financial Institutions',
        ],

        'health_and_social_care' => [
            'Health and Social Care Systems',
            'Human Development and Growth',
            'Health and Well-being',
            'Communication Skills in Health and Social Care',
            'Person-Centred Care',
            'Safeguarding and Protection',
            'Mental Health and Well-being',
            'Healthcare Professionals and Roles',
            'Health and Social Care Legislation and Policies',
            'Diversity and Equality in Health and Social Care',
            'Health Promotion and Public Health',
            'Care of Older Adults',
            'Chronic and Acute Illnesses',
            'Ethical Issues in Health and Social Care',
            'Medical Ethics',
            'Social Care and Disability',
            'Social Policy and Health Inequality',
            'End-of-life Care',
        ],
        'ict' => [
            'Computer Hardware and Components',
            'Software Applications and Development',
            'Data Storage and Management',
            'Programming and Coding (e.g., Python, JavaScript)',
            'Algorithms and Data Structures',
            'Database Design and Management',
            'Networks and Networking Protocols',
            'Cybersecurity and Ethical Hacking',
            'Web Development (HTML, CSS, JavaScript)',
            'Cloud Computing and Virtualization',
            'Operating Systems (Windows, Linux, macOS)',
            'Data Privacy and Encryption',
            'Social Media and Online Safety',
            'Artificial Intelligence and Machine Learning',
            'E-commerce and Digital Marketing',
            'Mobile App Development',
            'Technology in Society and Ethical Issues',
        ],

        'media_studies' => [
            'Media Theories (e.g., Uses and Gratifications, Hypodermic Needle Theory)',
            'Media Representation and Stereotypes',
            'Audience Theories and Audience Reception',
            'Media and Identity',
            'Media Regulation and Censorship',
            'Social Media and Digital Platforms',
            'Film Studies (Genres, Narrative Structures, etc.)',
            'Television Studies and Broadcast Media',
            'Radio and Podcasts',
            'Advertising and Marketing in Media',
            'Journalism and News Reporting',
            'New Media and Digital Journalism',
            'Media and Globalization',
            'Media Ethics and the Role of the Media',
            'Media Production (Film, TV, Digital Media)',
            'Media and Popular Culture',
            'Documentary and Factual Programming',
        ],

        'food_technology' => [
            'Food Safety and Hygiene',
            'Nutrition and Healthy Eating',
            'Food Processing and Preservation',
            'Food Production and Supply Chains',
            'Ingredients and Food Chemistry',
            'Meal Planning and Preparation',
            'Food Quality Control',
            'Global Food Production and Sustainability',
            'Cultural Influences on Food',
            'Food Labelling and Marketing',
            'Food Packaging and Design',
            'Catering and Hospitality Industry',
            'Food and Health Issues (e.g., Obesity, Food Allergies)',
            'Cooking Techniques and Methods',
            'Food Trends and Innovations',
            'Dietary Requirements and Special Diets',
            'Food Technology and Sustainability',
        ],

        'computer_science' => [
            'Algorithms and Problem Solving',
            'Programming Basics (Python, Java, or Scratch)',
            'Data Types and Variables',
            'Control Structures (Loops and Conditionals)',
            'Functions and Procedures',
            'Computer Hardware and Components',
            'Storage Devices and Memory',
            'Networking and the Internet',
            'Cybersecurity and Online Safety',
            'Binary and Data Representation',
            'Databases and SQL Basics',
            'Artificial Intelligence and Machine Learning Basics',
            'Software Development Life Cycle',
            'Computational Thinking',
            'Logic Gates and Boolean Algebra',
            'Operating Systems and File Management',
            'Cloud Computing and Virtualization',
            'Impacts of Digital Technology on Society',
            'Ethical Hacking and Encryption',
            'Game Development Basics',
        ],

    ]
];
